In [41]:
#TASK 1:Make three dataframe in python and save them as three .csv files. From Task 2 to Task 10, use the saved .csv files only. 

import numpy as np  # Import the NumPy library 
import pandas as pd  # Import the Pandas library

# 1. Recreate the raw Project dataset exactly as specified in the Capstone 
project_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005', 'A002', 'A005', 'A003', 'A001', 'A003', 'A001', 'A004', 'A004', 'A005'],  # Storing datas from Project Dataframe
    'Project': ['Project 1', 'Project 2', 'Project 3', 'Project 4', 'Project 5', 'Project 6', 'Project 7', 'Project 8', 'Project 9', 'Project 10', 'Project 11', 'Project 12', 'Project 13', 'Project 14'],  
    'Cost': [1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 350000, np.nan, 300000, 2000000, 1000000, 3000000, 200000],  
    'Status': ['Finished', 'Ongoing', 'Finished', 'Ongoing', 'Finished', 'Failed', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Finished'],  
}
df_project = pd.DataFrame(project_data)  # Convert the raw project dictionary data into a structured Pandas DataFrame

# 2. Recreate the raw Employee dataset exactly as specified in the Capstone project file
employee_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],  # Take all values from employee table 
    'Name': ['John Alter', 'Alice Luxumberg', 'Tom Sabestine', 'Nina Adgra', 'Amy Johny'],  
    'Gender': ['M', 'F', 'M', 'F', 'F'],  
    'City': ['Paris', 'London', 'Berlin', 'Newyork', 'Madrid'],  
    'Age': [25, 27, 30, 34, 26]  
}
df_employee = pd.DataFrame(employee_data)  # Convert the raw employee dictionary data into a structured Pandas DataFrame

# 3. Recreate the raw Seniority dataset exactly as specified in the Capstone 
seniority_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],  # Take all values from seniority table
    'Designation Level': [2, 2, 3, 2, 1]  
}
df_seniority = pd.DataFrame(seniority_data)  # Convert the raw seniority dictionary data into a structured Pandas DataFrame

# 4. Save each isolated DataFrame straight into clean, separate local CSV layers
df_project.to_csv('Project.csv', index=False)  # Save the project tracking table cleanly without internal index numbers
df_employee.to_csv('Employee.csv', index=False)  # Save the employee tracking table cleanly without internal index numbers
df_seniority.to_csv('Seniority.csv', index=False)  # Save the seniority tracking table cleanly without internal index numbers

print("Task 1 complete: All 3 CSV files successfully generated and written to disk.")  # Print a success status confirmation message

Task 1 complete: All 3 CSV files successfully generated and written to disk.

In [42]:
from IPython.display import display # Import specialized display utilities to render multiple tables

# Display the full content of all dataframes side by side or sequentially for us to view
print("--- 1. FULL PROJECT DATAFRAME ---")
display(df_project)

print("\n--- 2. FULL EMPLOYEE DATAFRAME ---")
display(df_employee)

print("\n--- 3. FULL SENIORITY DATAFRAME ---")
display(df_seniority)

--- 1. FULL PROJECT DATAFRAME ---

      ID     Project       Cost    Status
0   A001   Project 1 1002000.00  Finished
1   A002   Project 2 2000000.00   Ongoing
2   A003   Project 3 4500000.00  Finished
3   A004   Project 4 5500000.00   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6  680000.00    Failed
6   A005   Project 7  400000.00  Finished
7   A003   Project 8  350000.00    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10  300000.00  Finished
10  A001  Project 11 2000000.00    Failed
11  A004  Project 12 1000000.00   Ongoing
12  A004  Project 13 3000000.00  Finished
13  A005  Project 14  200000.00  Finished

--- 2. FULL EMPLOYEE DATAFRAME ---

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   30
3  A004       Nina Adgra      F  Newyork   34
4  A005        Amy Johny      F   Madrid   26

--- 3. FULL SENIORITY DATAFRAME ---

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  1

In [43]:
#TASK 2: The cost column in the dataframe “Project” has some missing values. Your task is to compute these missing values. Replace the missing values by running average. You should use the “For” loop for this task. 

import pandas as pd  # Import the Pandas library

df_p = pd.read_csv('Project.csv')  # Load  Project dataset CSV into active workspace memory

running_sum = 0  # Initialize variable tracking the sum of valid costs found up to current index
running_count = 0  # Initialize variable tracking the count of valid rows found up to current index

for i in range(len(df_p)):  # Loop step-by-step through every row index position across the dataset
    current_cost = df_p.loc[i, 'Cost']  # Extract the individual project cost entry value for the current active row
    
    if not pd.isna(current_cost):  # Check if the extracted cost cell value is a valid numeric number
        running_sum += current_cost  # Add the current valid project cost amount to our running sum tracker
        running_count += 1  # Increment our row counter tracker of valid records by one unit
    else:  # Run alternative mathematical logic if the current cost cell matches missing NaN criteria
        running_avg = running_sum / running_count  # Calculate running average by dividing total sum by total valid count
        df_p.loc[i, 'Cost'] = running_avg  # Insert the calculated running average back into the empty dataframe cell
        running_sum += running_avg  # Add the newly calculated average value directly into our rolling sum memory
        running_count += 1  # Increment our running row counter to properly include this newly updated cell

# Force notebook to show clean float currencies instead of raw scientific notation
pd.set_option('display.float_format', lambda x: '%.2f' % x)

df_p.to_csv('Project.csv', index=False)  # Save the finalized project dataframe back to its CSV layer
df_p  # Print out  project table

      ID     Project       Cost    Status
0   A001   Project 1 1002000.00  Finished
1   A002   Project 2 2000000.00   Ongoing
2   A003   Project 3 4500000.00  Finished
3   A004   Project 4 5500000.00   Ongoing
4   A005   Project 5 3250500.00  Finished
5   A002   Project 6  680000.00    Failed
6   A005   Project 7  400000.00  Finished
7   A003   Project 8  350000.00    Failed
8   A001   Project 9 2210312.50   Ongoing
9   A003  Project 10  300000.00  Finished
10  A001  Project 11 2000000.00    Failed
11  A004  Project 12 1000000.00   Ongoing
12  A004  Project 13 3000000.00  Finished
13  A005  Project 14  200000.00  Finished

In [44]:
#TASK 3: Split the name column in the Employee dataframe into two new columns “First Name”, and “Last Name” and remove the older “name” column. 

import pandas as pd # Import the Pandas library

df_emp = pd.read_csv("Employee.csv") # Load dataset from Task 1

df_emp[["First Name", "Last Name"]] = df_emp["Name"].str.split(" ", n=1, expand=True) # Split at the first space into the two columns

df_emp.drop(columns=["Name"], inplace=True) # Drop old column and save file

df_emp.to_csv("Employee.csv", index=False) # Saves the updated DataFrame to a CSV file while omitting row index numbers

df_emp #Evaluates and displays the DataFrame

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   30        Tom  Sabestine
3  A004      F  Newyork   34       Nina      Adgra
4  A005      F   Madrid   26        Amy      Johny

In [45]:
#TASK 4: Join all three dataframes in one single dataframe. Name it “Final” 

import pandas as pd  # Import the Pandas library 

df_p = pd.read_csv('Project.csv')  # Load  Project dataset CSV into active memory
df_e = pd.read_csv('Employee.csv')  # Load  split-name Employee dataset CSV into active memory
df_s = pd.read_csv('Seniority.csv')  # Load  raw Seniority level dataset CSV into active memory

df_merged_emp = pd.merge(df_e, df_s, on='ID')  # Join the edited employee dataframe with the seniority dataframe matching along their unique shared employee ID field
Final = pd.merge(df_merged_emp, df_p, on='ID')  # Merge that intermediate table together with our updated project data table matching along the same ID column fields

Final.to_csv('Final.csv', index=False)  # Save the consolidated source-of-truth table directly as a new CSV layer
pd.set_option('display.float_format', lambda x: '%.2f' % x)  # Configure display format options to get clean decimals instead of unreadable scientific notations

Final  # Print out all 14 rows of table

      ID Gender     City  Age First Name  Last Name  Designation Level     Project       Cost    Status
0   A001      M    Paris   25       John      Alter                  2   Project 1 1002000.00  Finished
1   A001      M    Paris   25       John      Alter                  2   Project 9 2210312.50   Ongoing
2   A001      M    Paris   25       John      Alter                  2  Project 11 2000000.00    Failed
3   A002      F   London   27      Alice  Luxumberg                  2   Project 2 2000000.00   Ongoing
4   A002      F   London   27      Alice  Luxumberg                  2   Project 6  680000.00    Failed
5   A003      M   Berlin   30        Tom  Sabestine                  3   Project 3 4500000.00  Finished
6   A003      M   Berlin   30        Tom  Sabestine                  3   Project 8  350000.00    Failed
7   A003      M   Berlin   30        Tom  Sabestine                  3  Project 10  300000.00  Finished
8   A004      F  Newyork   34       Nina      Adgra                  2   Project 4 5500000.00   Ongoing
9   A004      F  Newyork   34       Nina      Adgra                  2  Project 12 1000000.00   Ongoing
10  A004      F  Newyork   34       Nina      Adgra                  2  Project 13 3000000.00  Finished
11  A005      F   Madrid   26        Amy      Johny                  1   Project 5 3250500.00  Finished
12  A005      F   Madrid   26        Amy      Johny                  1   Project 7  400000.00  Finished
13  A005      F   Madrid   26        Amy      Johny                  1  Project 14  200000.00  Finished

In [46]:
#TASK 5: Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project cost only to employees who have finished the projects.

import numpy as np  # Import the NumPy library 
import pandas as pd  # Import the Pandas library 

Final = pd.read_csv('Final.csv')  # Load combined master dataset from the saved CSV file

# Compute the bonus: 5% of cost if Status is Finished, otherwise set it strictly to 0.0
Final['Bonus'] = np.where(Final['Status'] == 'Finished', Final['Cost'] * 0.05, 0.0)

Final.to_csv('Final.csv', index=False)  # Save updated dataframe with the new bonus column back to CSV
Final  # Print out all rows of table

      ID Gender     City  Age First Name  Last Name  Designation Level     Project       Cost    Status     Bonus
0   A001      M    Paris   25       John      Alter                  2   Project 1 1002000.00  Finished  50100.00
1   A001      M    Paris   25       John      Alter                  2   Project 9 2210312.50   Ongoing      0.00
2   A001      M    Paris   25       John      Alter                  2  Project 11 2000000.00    Failed      0.00
3   A002      F   London   27      Alice  Luxumberg                  2   Project 2 2000000.00   Ongoing      0.00
4   A002      F   London   27      Alice  Luxumberg                  2   Project 6  680000.00    Failed      0.00
5   A003      M   Berlin   30        Tom  Sabestine                  3   Project 3 4500000.00  Finished 225000.00
6   A003      M   Berlin   30        Tom  Sabestine                  3   Project 8  350000.00    Failed      0.00
7   A003      M   Berlin   30        Tom  Sabestine                  3  Project 10  300000.00  Finished  15000.00
8   A004      F  Newyork   34       Nina      Adgra                  2   Project 4 5500000.00   Ongoing      0.00
9   A004      F  Newyork   34       Nina      Adgra                  2  Project 12 1000000.00   Ongoing      0.00
10  A004      F  Newyork   34       Nina      Adgra                  2  Project 13 3000000.00  Finished 150000.00
11  A005      F   Madrid   26        Amy      Johny                  1   Project 5 3250500.00  Finished 162525.00
12  A005      F   Madrid   26        Amy      Johny                  1   Project 7  400000.00  Finished  20000.00
13  A005      F   Madrid   26        Amy      Johny                  1  Project 14  200000.00  Finished  10000.00

In [47]:
#TASK 6: Demote the designation level by 1, whose projects have status “fail”. Delete the employees record whose designation level is above 4.

import numpy as np  # Import the NumPy library 
import pandas as pd  # Import the Pandas library 

Final = pd.read_csv('Final.csv')  # Load your combined master dataset from the saved CSV file

# If status is Failed, add 1 to Designation Level; otherwise, keep the current Designation Level intact
Final['Designation Level'] = np.where(Final['Status'] == 'Failed', Final['Designation Level'] + 1, Final['Designation Level'])

# Drop rows by preserving only those records where the Designation Level does not exceed 4
Final = Final[Final['Designation Level'] <= 4]

Final.to_csv('Final.csv', index=False)  # Save penalty dataframe back to the CSV layer
Final

      ID Gender     City  Age First Name  Last Name  Designation Level     Project       Cost    Status     Bonus
0   A001      M    Paris   25       John      Alter                  2   Project 1 1002000.00  Finished  50100.00
1   A001      M    Paris   25       John      Alter                  2   Project 9 2210312.50   Ongoing      0.00
2   A001      M    Paris   25       John      Alter                  3  Project 11 2000000.00    Failed      0.00
3   A002      F   London   27      Alice  Luxumberg                  2   Project 2 2000000.00   Ongoing      0.00
4   A002      F   London   27      Alice  Luxumberg                  3   Project 6  680000.00    Failed      0.00
5   A003      M   Berlin   30        Tom  Sabestine                  3   Project 3 4500000.00  Finished 225000.00
6   A003      M   Berlin   30        Tom  Sabestine                  4   Project 8  350000.00    Failed      0.00
7   A003      M   Berlin   30        Tom  Sabestine                  3  Project 10  300000.00  Finished  15000.00
8   A004      F  Newyork   34       Nina      Adgra                  2   Project 4 5500000.00   Ongoing      0.00
9   A004      F  Newyork   34       Nina      Adgra                  2  Project 12 1000000.00   Ongoing      0.00
10  A004      F  Newyork   34       Nina      Adgra                  2  Project 13 3000000.00  Finished 150000.00
11  A005      F   Madrid   26        Amy      Johny                  1   Project 5 3250500.00  Finished 162525.00
12  A005      F   Madrid   26        Amy      Johny                  1   Project 7  400000.00  Finished  20000.00
13  A005      F   Madrid   26        Amy      Johny                  1  Project 14  200000.00  Finished  10000.00

In [48]:
#TASK 7: Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

import numpy as np  # Import the NumPy library 
import pandas as pd  # Import the Pandas library

Final = pd.read_csv('Final.csv')  # Load dataset from the saved CSV file

if 'Gender' in Final.columns:  # Check if the Gender column exists before transforming to prevent re-run errors
    Final['First Name'] = np.where(Final['Gender'] == 'M', 'Mr. ' + Final['First Name'], 'Mrs. ' + Final['First Name'])  # Prepend 'Mr. ' or 'Mrs. ' to the First Name based on Gender criteria
    Final = Final.drop(columns=['Gender'], errors='ignore')  # Drop binary Gender classification column directly from  memory to clean the layout

Final.to_csv('Final.csv', index=False)  # Save  dataframe structure back to the CSV layer
Final  # Print out all rows of table

      ID     City  Age  First Name  Last Name  Designation Level     Project       Cost    Status     Bonus
0   A001    Paris   25    Mr. John      Alter                  2   Project 1 1002000.00  Finished  50100.00
1   A001    Paris   25    Mr. John      Alter                  2   Project 9 2210312.50   Ongoing      0.00
2   A001    Paris   25    Mr. John      Alter                  3  Project 11 2000000.00    Failed      0.00
3   A002   London   27  Mrs. Alice  Luxumberg                  2   Project 2 2000000.00   Ongoing      0.00
4   A002   London   27  Mrs. Alice  Luxumberg                  3   Project 6  680000.00    Failed      0.00
5   A003   Berlin   30     Mr. Tom  Sabestine                  3   Project 3 4500000.00  Finished 225000.00
6   A003   Berlin   30     Mr. Tom  Sabestine                  4   Project 8  350000.00    Failed      0.00
7   A003   Berlin   30     Mr. Tom  Sabestine                  3  Project 10  300000.00  Finished  15000.00
8   A004  Newyork   34   Mrs. Nina      Adgra                  2   Project 4 5500000.00   Ongoing      0.00
9   A004  Newyork   34   Mrs. Nina      Adgra                  2  Project 12 1000000.00   Ongoing      0.00
10  A004  Newyork   34   Mrs. Nina      Adgra                  2  Project 13 3000000.00  Finished 150000.00
11  A005   Madrid   26    Mrs. Amy      Johny                  1   Project 5 3250500.00  Finished 162525.00
12  A005   Madrid   26    Mrs. Amy      Johny                  1   Project 7  400000.00  Finished  20000.00
13  A005   Madrid   26    Mrs. Amy      Johny                  1  Project 14  200000.00  Finished  10000.00

In [49]:
#TASK 8: Promote designation level by 1 for the employees whose age is more than 29 years using IF condition. 

import numpy as np  # Import the NumPy library 
import pandas as pd  # Import the Pandas library 

Final = pd.read_csv('Final.csv')  # Load dataset from the saved CSV file

# Promote employees older than 29 by subtracting 1 from their Designation Level; otherwise, keep it the same
Final['Designation Level'] = np.where(Final['Age'] > 29, Final['Designation Level'] - 1, Final['Designation Level'])

Final.to_csv('Final.csv', index=False)  # Save promotion modified master dataframe back to CSV
Final  # Print

      ID     City  Age  First Name  Last Name  Designation Level     Project       Cost    Status     Bonus
0   A001    Paris   25    Mr. John      Alter                  2   Project 1 1002000.00  Finished  50100.00
1   A001    Paris   25    Mr. John      Alter                  2   Project 9 2210312.50   Ongoing      0.00
2   A001    Paris   25    Mr. John      Alter                  3  Project 11 2000000.00    Failed      0.00
3   A002   London   27  Mrs. Alice  Luxumberg                  2   Project 2 2000000.00   Ongoing      0.00
4   A002   London   27  Mrs. Alice  Luxumberg                  3   Project 6  680000.00    Failed      0.00
5   A003   Berlin   30     Mr. Tom  Sabestine                  2   Project 3 4500000.00  Finished 225000.00
6   A003   Berlin   30     Mr. Tom  Sabestine                  3   Project 8  350000.00    Failed      0.00
7   A003   Berlin   30     Mr. Tom  Sabestine                  2  Project 10  300000.00  Finished  15000.00
8   A004  Newyork   34   Mrs. Nina      Adgra                  1   Project 4 5500000.00   Ongoing      0.00
9   A004  Newyork   34   Mrs. Nina      Adgra                  1  Project 12 1000000.00   Ongoing      0.00
10  A004  Newyork   34   Mrs. Nina      Adgra                  1  Project 13 3000000.00  Finished 150000.00
11  A005   Madrid   26    Mrs. Amy      Johny                  1   Project 5 3250500.00  Finished 162525.00
12  A005   Madrid   26    Mrs. Amy      Johny                  1   Project 7  400000.00  Finished  20000.00
13  A005   Madrid   26    Mrs. Amy      Johny                  1  Project 14  200000.00  Finished  10000.00

In [50]:
#TASK 9: Add the cost of all projects for each Employee and save it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost

import pandas as pd  # Import the Pandas library

Final = pd.read_csv('Final.csv')  # Load  promotion modified master dataset from the saved CSV file

# Group by ID and First Name, calculate the sum of the Cost column, and reset the index to keep a flat table layout
summary_df = Final.groupby(['ID', 'First Name'])['Cost'].sum().reset_index()

# Rename the aggregated sum calculation column directly to 'Total cost' to match submission criteria
summary_df = summary_df.rename(columns={'Cost': 'Total cost'})

summary_df.to_csv('Summary_Task9.csv', index=False)  # Save the  aggregate summary layer directly to a fresh CSV file
summary_df  # Display the complete generated summary dataset output metrics on notebook screen

     ID  First Name  Total cost
0  A001    Mr. John  5212312.50
1  A002  Mrs. Alice  2680000.00
2  A003     Mr. Tom  5150000.00
3  A004   Mrs. Nina  9500000.00
4  A005    Mrs. Amy  3850500.00

In [53]:
#TASK 10: Print all the employee details whose city name contains the letter “o” in it. 

import pandas as pd  # Import the Pandas library package utilities

Final = pd.read_csv('Final.csv')  # Load master consolidated dataset file back into memory

# Set global display width limits to 1000 characters to prevent columns from wrapping vertically on screen
pd.set_option('display.width', 1000)

# Filter the master table to keep rows where the City name contains the letter 'o' (case-insensitive check)
final_report = Final[Final['City'].str.contains('o', case=False)]

# Save this final extracted target regional slice out into a persistent reporting CSV file layer
final_report.to_csv('Final_Report_Task10.csv', index=False)

final_report  # Display the completed clean horizontal output tracking grid on  workspace window

      ID     City  Age  First Name  Last Name  Designation Level     Project       Cost    Status     Bonus
3   A002   London   27  Mrs. Alice  Luxumberg                  2   Project 2 2000000.00   Ongoing      0.00
4   A002   London   27  Mrs. Alice  Luxumberg                  3   Project 6  680000.00    Failed      0.00
8   A004  Newyork   34   Mrs. Nina      Adgra                  1   Project 4 5500000.00   Ongoing      0.00
9   A004  Newyork   34   Mrs. Nina      Adgra                  1  Project 12 1000000.00   Ongoing      0.00
10  A004  Newyork   34   Mrs. Nina      Adgra                  1  Project 13 3000000.00  Finished 150000.00